<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dessins</title>
</head>
<body>
    <h1>Dessins</h1>
    
    <!--Ancienne Methode-->
    <!--<svg width="800" height="600">-->
        
        <!--Ancienne methode -->
        <!--<?= $rectangle->draw() ?>-->
        <!--<?= $ellipse->draw() ?>-->
        <!--<?= $triangle->draw() ?>-->
        
        <!--Methode RENDER-->
         <?= $container->render() ?>
        
    <!--</svg>-->
</body>
</html>